<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="DTOs\NewFolder\**" />
      <EmbeddedResource Remove="DTOs\NewFolder\**" />
      <None Remove="DTOs\NewFolder\**" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Vivu.Domain\Vivu.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="13.0.1" />
      <PackageReference Include="FluentValidation" Version="12.1.1" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
      <PackageReference Include="MediatR" Version="14.0.0" />
      <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.9" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.22" />
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.1" />
    </ItemGroup>
    <ItemGroup>
      <Folder Include="UseCases\Auth\Queries\" />
      <Folder Include="UseCases\ChatMessages\Queries\" />
      <Folder Include="UseCases\Users\Commands\" />
    </ItemGroup>

</Project>
